application: pystok-modules
version: 002
api_version: 1
runtime: python27
threadsafe: true
instance_class: F1

builtins:
- deferred: on

inbound_services:
- warmup

libraries:
- name: jinja2
  version: "2.6"
- name: webapp2
  version: "2.5.2"

handlers:
- url: .*
  script: app.main.app
  secure: never
